#!/usr/bin/env bash
# shellcheck disable=SC1091
. ./function_post_install.sh
DEFAULTPASSWD=test
MARIADB_ROOT_PWD="${1:-$DEFAULTPASSWD}"



# Install and configure Maria-DB
print_color "green" "Installing MariaDB Server.."
apt install -y mariadb-server
sudo mariadb-secure-installation << EOF
> $MARIADB_ROOT_PWD
> n
> n
> Y
> Y
> Y
> Y
> EOF

print_color "green" "Starting MariaDB Server.."
sudo service mariadb start
sudo systemctl enable mariadb
check_service_status mariadb

# Configuring Database
print_color "green" "Setting up database.."
cat > setup-db.sql <<-EOF
  CREATE DATABASE $DBNAME;
  CREATE USER '$DBUSER'@'localhost' IDENTIFIED BY '$DBUSER_PWD';
  GRANT ALL PRIVILEGES ON *.* TO '$DBUSER'@'localhost';
  FLUSH PRIVILEGES;
EOF
mysql < setup-db.sql
