---
services:
  wordpress:
    image: wordpress:php8.3-apache
    container_name: wordpress
    hostname: wordpress.local  # Set the hostname for the WordPress container
    networks:
      - frontend
      - backend
    logging:
      driver: syslog

  mariadb:
    image: mariadb:11.2
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234  # Set the root password for MariaDB (will be reset by init script)
    volumes:
      - /srv/mariadb:/var/lib/mysql  # Persist the MariaDB data in a Docker volume
      - ./initfile.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1  # Allow arbitrary server connections
      - PMA_HOST=mariadb  # Set the default server to 'mariadb'
    depends_on:
      - mariadb  # Ensure the MariaDB container starts before phpMyAdmin
    hostname: phpmyadmin.local
    networks:
      - frontend
      - backend

  npm:
    image: jc21/nginx-proxy-manager:github-pr-3789
    container_name: npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - web
      - frontend

volumes:
  mariadb-data:  # Define the Docker volume for MariaDB data

networks:
  web:
    name: web-network
  frontend:
    name: frontend-network  # Name the frontend network 'frontend-network'
    internal: true
  backend:
    name: backend-network  # Name the backend network 'backend-network'
    internal: true  # Make the backend network internal (not accessible from outside Docker)
    ipam: # Network configuration
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
          aux_addresses:  # Assign specific IP addresses to services
            wordpress: 172.28.1.5
            phpmyadmin: 172.28.1.6
            mariadb: 172.28.1.7
