virt-install										\
	--console=pty,target_type=serial						\
	--disk=pool=default,size=20,format=qcow2,bus=virtio				\
	--extra-args="auto console=ttyS0, 115200n8 serial"				\
	--extra-args="ks=file:preseed.cfg"						\
	--graphics=none									\
	--initrd-inject=preseed.cfg							\
	--location=/home/journiac/Téléchargements/debian-12.5.0-amd64-netinst.iso	\
	--memory=4096									\
	--name=new-vm									\
	--network=default,model=virtio							\
	--os-variant=debian12								\
	--vcpus=4
