---
############
### CRON ###
############
---
kind: CronJob
metadata:
  name: dump
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: dump
              image: mariadb:10.6.18
              command: ["/bin/bash", "-c", "mysqldump -h sql-01 -u admin -proot mydb > /docker-entrypoint-initdb.d/backup/mydb__$(date +'%Y%m%d_%H%M%S').sql"]
              volumeMounts:
                - name: dump
                  mountPath: /docker-entrypoint-initdb.d/backup
          restartPolicy: OnFailure
          volumes:
            - name: dump
              persistentVolumeClaim:
                claimName: pvc
apiVersion: batch/v1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
